/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_LANE_ASSISTANCE_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_LANE_ASSISTANCE_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/LaneAssistanceStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::LaneAssistanceStub, typename... _Stubs>
class LaneAssistanceSomeIPStubAdapterInternal
    : public virtual LaneAssistanceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> LaneAssistanceSomeIPStubAdapterHelper;

    ~LaneAssistanceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        LaneAssistanceSomeIPStubAdapterHelper::deinit();
    }

    void fireSteeringAttributeChanged(const std::string &_value);
    
    void fireThrottleAttributeChanged(const std::string &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::LaneAssistanceStub,
        CommonAPI::Version
    > getLaneAssistanceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::LaneAssistanceStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getSteeringAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::LaneAssistanceStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getThrottleAttributeStubDispatcher;
    
    LaneAssistanceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        LaneAssistanceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< LaneAssistanceStub>(_stub)),
        getLaneAssistanceInterfaceVersionStubDispatcher(&LaneAssistanceStub::lockInterfaceVersionAttribute, &LaneAssistanceStub::getInterfaceVersion, false, true),
        getSteeringAttributeStubDispatcher(
            &::v0::commonapi::LaneAssistanceStub::lockSteeringAttribute,
            &::v0::commonapi::LaneAssistanceStub::getSteeringAttribute,
            false,
            _stub->hasElement(0))
        ,
        getThrottleAttributeStubDispatcher(
            &::v0::commonapi::LaneAssistanceStub::lockThrottleAttribute,
            &::v0::commonapi::LaneAssistanceStub::getThrottleAttribute,
            false,
            _stub->hasElement(1))
    {
        LaneAssistanceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1bbd) }, &getSteeringAttributeStubDispatcher );
        LaneAssistanceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1c21) }, &getThrottleAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1bbc)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x11558), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireSteeringAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::LaneAssistanceStub>(_stub)->getSteeringAttribute(itsClient));
        }

        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x1c20)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x11940), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireThrottleAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::LaneAssistanceStub>(_stub)->getThrottleAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSteeringAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x11558),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireThrottleAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x11940),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::LaneAssistanceStub, typename... _Stubs>
class LaneAssistanceSomeIPStubAdapter
    : public LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    LaneAssistanceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          LaneAssistanceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_Lane_Assistance_SOMEIP_STUB_ADAPTER_HPP_
